project_id = "sgfpvrfjgzwsjwduibhm"

[functions.sync-portal]
verify_jwt = false

[functions.get-portal]
verify_jwt = false

[functions.upload-photo]
verify_jwt = false

[functions.upload-diagnostic]
verify_jwt = false

[functions.sync-data]
verify_jwt = false
