// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
async function loadWorkspaceData(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data: mem, error: memErr } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true }).limit(1).maybeSingle();
  if (memErr) throw new Error(memErr.message);
  if (!mem) throw new Error("No workspace found for user");
  const { data: sync, error: syncErr } = await supabase.from("app_sync").select("data").eq("workspace_id", mem.workspace_id).maybeSingle();
  if (syncErr) throw new Error(syncErr.message);
  return { workspaceId: mem.workspace_id, data: sync?.data || {} };
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients in the signed-in user's ChipTime workspace, optionally filtered by a name/email substring search.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive substring match against name, email, or company."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data } = await loadWorkspaceData(ctx);
    let clients = Array.isArray(data.clients) ? data.clients : [];
    if (search) {
      const q = search.toLowerCase();
      clients = clients.filter(
        (c) => [c.name, c.email, c.companyName, c.phone].filter(Boolean).some((v) => String(v).toLowerCase().includes(q))
      );
    }
    const rows = clients.slice(0, limit ?? 50).map((c) => ({
      id: c.id,
      name: c.name,
      email: c.email,
      phone: c.phone,
      companyName: c.companyName,
      prepaidAmount: c.prepaidAmount
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { clients: rows, total: clients.length }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
async function loadWorkspaceData2(ctx) {
  const supabase = supabaseForUser2(ctx);
  const { data: mem, error: memErr } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true }).limit(1).maybeSingle();
  if (memErr) throw new Error(memErr.message);
  if (!mem) throw new Error("No workspace found");
  const { data: sync } = await supabase.from("app_sync").select("data").eq("workspace_id", mem.workspace_id).maybeSingle();
  return sync?.data || {};
}
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List tasks",
  description: "List work tasks in the user's ChipTime workspace. Filter by status and/or client. Sessions and photos are omitted; use get_task for details.",
  inputSchema: {
    status: z2.enum(["pending", "in-progress", "paused", "completed", "billed", "paid"]).optional().describe("Filter by task status."),
    clientId: z2.string().optional().describe("Filter to tasks for a specific client id."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, clientId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const data = await loadWorkspaceData2(ctx);
    const clientsById = new Map(
      (data.clients || []).map((c) => [c.id, c])
    );
    let tasks = Array.isArray(data.tasks) ? data.tasks : [];
    if (status) tasks = tasks.filter((t) => t.status === status);
    if (clientId) tasks = tasks.filter((t) => t.clientId === clientId);
    tasks.sort(
      (a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
    );
    const rows = tasks.slice(0, limit ?? 50).map((t) => ({
      id: t.id,
      status: t.status,
      customerName: t.customerName || clientsById.get(t.clientId)?.name,
      carVin: t.carVin,
      totalTimeSeconds: t.totalTime,
      createdAt: t.createdAt,
      paidAt: t.paidAt,
      sessionCount: (t.sessions || []).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { tasks: rows, total: tasks.length }
    };
  }
});

// src/lib/mcp/tools/get-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_task_default = defineTool3({
  name: "get_task",
  title: "Get task detail",
  description: "Fetch a single ChipTime task with its work sessions, parts, jobs, and billing status. Photo binary data is omitted.",
  inputSchema: {
    taskId: z3.string().min(1).describe("Task id (from list_tasks).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ taskId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data: mem } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (!mem) return { content: [{ type: "text", text: "No workspace" }], isError: true };
    const { data: sync } = await supabase.from("app_sync").select("data").eq("workspace_id", mem.workspace_id).maybeSingle();
    const data = sync?.data || {};
    const task = (data.tasks || []).find((t) => t.id === taskId);
    if (!task) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    const client = (data.clients || []).find((c) => c.id === task.clientId);
    const vehicle = (data.vehicles || []).find((v) => v.id === task.vehicleId);
    const sessions = (task.sessions || []).map((s) => ({
      id: s.id,
      description: s.description,
      createdAt: s.createdAt,
      completedAt: s.completedAt,
      periods: (s.periods || []).map((p) => ({
        startTime: p.startTime,
        endTime: p.endTime,
        duration: p.duration
      })),
      parts: s.parts || [],
      jobs: s.jobs || [],
      extraCharge: s.extraCharge,
      photoCount: (s.photos || []).length
    }));
    const detail = {
      id: task.id,
      status: task.status,
      customerName: task.customerName || client?.name,
      carVin: task.carVin,
      vehicle: vehicle ? { year: vehicle.year, make: vehicle.make, model: vehicle.model, color: vehicle.color } : null,
      totalTimeSeconds: task.totalTime,
      createdAt: task.createdAt,
      paidAt: task.paidAt,
      needsFollowUp: task.needsFollowUp,
      importedSalary: task.importedSalary,
      sessions
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-schedule.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_schedule_default = defineTool4({
  name: "list_schedule",
  title: "List scheduled jobs",
  description: "List upcoming or open ChipTime schedule entries (jobs planned but not yet started).",
  inputSchema: {
    status: z4.enum(["scheduled", "started", "cancelled"]).optional().describe("Filter by schedule status (default: scheduled)."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data: mem } = await supabase.from("workspace_members").select("workspace_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (!mem) return { content: [{ type: "text", text: "No workspace" }], isError: true };
    const { data: sync } = await supabase.from("app_sync").select("data").eq("workspace_id", mem.workspace_id).maybeSingle();
    const data = sync?.data || {};
    const clientsById = new Map((data.clients || []).map((c) => [c.id, c]));
    const vehiclesById = new Map((data.vehicles || []).map((v) => [v.id, v]));
    const filterStatus = status ?? "scheduled";
    let entries = (data.schedule || []).filter((s) => s.status === filterStatus);
    entries.sort(
      (a, b) => new Date(a.scheduledAt || a.createdAt || 0).getTime() - new Date(b.scheduledAt || b.createdAt || 0).getTime()
    );
    const rows = entries.slice(0, limit ?? 50).map((s) => {
      const client = clientsById.get(s.clientId);
      const vehicle = vehiclesById.get(s.vehicleId);
      return {
        id: s.id,
        client: client?.name,
        vehicle: vehicle ? `${vehicle.year ?? ""} ${vehicle.make ?? ""} ${vehicle.model ?? ""}`.trim() : null,
        requestedWork: s.requestedWork,
        scheduledAt: s.scheduledAt,
        notes: s.notes
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { entries: rows, total: entries.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sgfpvrfjgzwsjwduibhm";
var mcp_default = defineMcp({
  name: "chiptime-mcp",
  title: "ChipTime MCP",
  version: "0.1.0",
  instructions: "Read-only tools for ChipTime \u2014 an automotive service time & billing app. Use list_clients to find a customer, list_tasks to see current or completed work orders (filter by status), get_task for full session/parts/jobs detail on one work order, and list_schedule for upcoming jobs on the shop calendar. All calls act as the signed-in ChipTime user and are scoped to their workspace.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_tasks_default, get_task_default, list_schedule_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
